### ISSUE TITLE
Provide the resources

### ISSUE THREAD

**Issue by arv-anshul** [nitin7478/Credit-Card-Default-Prediction#1]
Hi @nitin7478 , I am Anshul. This project of yours is seems amazing to me because I can't imagine how beautifully you created pipelines to attach those components to work. I wonder where do you learn these concepts to create this type of pipelines. Can you share the resources here. It will be very helpful for and others.

### Resources

- From where did you learn this? Please provide the video, blog, GitHub repo links of those?
- If you done any other project like this in past or want to do in future please consider those to share as well.

Please share them. I need to learn those things.
Thank You!

**Comment by nitin7478** [comment]
Pipeline taught by Avnish Yadav : https://github.com/avnyadav at iNeuron.ai
